// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/onboarding/Screen1.tsx": () => import("../components/mockups/onboarding/Screen1.tsx"),
  "./components/mockups/onboarding/Screen2.tsx": () => import("../components/mockups/onboarding/Screen2.tsx"),
  "./components/mockups/onboarding/Screen3.tsx": () => import("../components/mockups/onboarding/Screen3.tsx"),
  "./components/mockups/onboarding/Screen4.tsx": () => import("../components/mockups/onboarding/Screen4.tsx"),
  "./components/mockups/practice-redesign/ConceptA_Glow.tsx": () => import("../components/mockups/practice-redesign/ConceptA_Glow.tsx"),
  "./components/mockups/practice-redesign/ConceptB_VerbCard.tsx": () => import("../components/mockups/practice-redesign/ConceptB_VerbCard.tsx"),
  "./components/mockups/practice-redesign/VariantA.tsx": () => import("../components/mockups/practice-redesign/VariantA.tsx"),
  "./components/mockups/practice-redesign/VariantB.tsx": () => import("../components/mockups/practice-redesign/VariantB.tsx"),
  "./components/mockups/practice-redesign/VariantC.tsx": () => import("../components/mockups/practice-redesign/VariantC.tsx")
};
